### PR TITLE
Add support for Elixir [WIP]

### PR DESCRIPTION
**Pull request by greysteil**
A starting point for adding Elixir support.

Next step would be to write a parser for the `mix.lock` file, in Elixir. The [JavaScript helper run task](https://github.com/gocardless/bump-core/blob/master/helpers/javascript/bin/run.js) and [parser](https://github.com/gocardless/bump-core/blob/master/helpers/javascript/lib/parser.js) are the best places to start for understanding how shelling out to helpers works. We'll probably want to piggy back off of `Hex` as much as possible here, and include it as a dependency (like we do with Yarn).

Once an Elixir parser is written, the pending specs in `spec/bump/file_parsers/elixir/hex_spec.rb` should pass. At that point, let's talk about adding the `UpdateChecker`, `FileUpdater` and `MetadataFinder` classes.

### CODE REVIEW

**Comment by greysteil** [comment]
@stevedomin - a starting point if you want to take a crack 😄

**Comment by andrew** [comment]
@greysteil I've written a mix parser for https://libraries.io, it's over here: https://github.com/librariesio/mix-deps-json

**Comment by greysteil** [comment]
Nice, thanks @andrew !

**Comment by stevedomin** [comment]
Hi @greysteil, looking at this over the week-end!

**Comment by greysteil** [comment]
Closing in favour of https://github.com/dependabot/dependabot-core/pull/10

**Pull request closed without merging**
